### ISSUE TITLE
技術検証 - Serverless FrameworkでLambda関数をデプロイ

### ISSUE THREAD

**Issue by kawabata2018** [makes-trail/application-sample#13]
### 背景

- https://github.com/makes-trail/trail-management/issues/6
- 作成するLambda関数が増えていくと、いちいち手でzip化してAWSにアップロードするのは手間がかかる
- Serverless Frameworkを使えばコマンド一発でデプロイが完了する
- これを活用しない手はない

### To do

- `Psycopg2`などPure Pythonでないパッケージを含んだLambda関数をAWSへデプロイできる
- 手順をまとめる

### 完了条件

- レビューをもらい（他の環境でも動作することを確認し）mainブランチにmergeされている

**Comment by kawabata2018** [comment]
## 参考記事

- [How to Handle your Python packaging in Lambda with Serverless plugins](https://www.serverless.com/blog/serverless-python-packaging)
- [Serverless Frameworkのプラグインを利用した外部モジュールの管理](https://dev.classmethod.jp/articles/managing-external-modules-with-serverless-framework-plugin/)
- [AWS LambdaでNumpy、Scipyを使ってみる！Serverless Frameworkとプラグインを使えばパッケージ管理が簡単！](https://dev.classmethod.jp/articles/serverless-framework-lambda-numpy-scipy/)

**Comment by kawabata2018** [comment]
```yaml
service: mt-sample
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  logRetentionInDays: 30
  versionFunctions: false
  timeout: 20
  deploymentBucket:
    name: mt-sample-${self:provider.stage}-deployment

package:
  individually: true

plugins:
  - serverless-python-requirements

custom:
  dynamedbTableName: mt-sample-dev

layers:
  requirements:
    package:
      artifact: layers/artifact/requirements.zip
    compatibleRuntimes:
      - python3.8
    retain: false

functions:
  hello:
    handler: handler.hello
    package:
      exclude:
        - '**'
      include:
        - handler.py
  fetch-openbd-summary:
    handler: main.handler
    layers:
      - {Ref: RequirementsLambdaLayer}
    package:
      artifact: functions/artifact/fetch_openbd_summary.zip
  save-openbd-to-ddb:
    handler: main.handler
    layers:
      - {Ref: RequirementsLambdaLayer}
    environment:
      DYNAMODB_TABLE: ${self:custom.dynamedbTableName}
    package:
      artifact: functions/artifact/save_openbd_to_ddb.zip

resources:
  Resources:
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: arn:aws:dynamodb:*:*:table/*
        Roles:
          - Ref: IamRoleLambdaExecution
```
