### ISSUE TITLE
技術検証 - Googleログイン

### ISSUE THREAD

**Issue by kawabata2018** [makes-trail/application-sample#39]
### 背景

- LINEログインはスマートフォン上から扱いにくいためGoogleログインを利用する（関連 #8）

### To do

- 簡易的なウェブアプリを実装して挙動を確認する
- CognitoにGoogle認証を連携させる
- Cognitoオーソライザ付きのAPI GatewayをServerless Frameworkを使用してデプロイする

### 完了条件

- 上記を満たした成果物がmainブランチにmergeされている

**Comment by kawabata2018** [comment]
## Serverless FrameworkでCognitoオーソライザの実装

> https://www.ragate.co.jp/blog/articles/5024

```yml
Resources:
  ApiGatewayWithAuthorizationAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    DependsOn:
      - ApiGatewayRestApi
    Properties:
      Name: ApiGatewayWithAuthorizationAuthorizer
      RestApiId:
        Ref: ApiGatewayRestApi
      IdentitySource: method.request.header.Authorization
      Type: COGNITO_USER_POOLS
      ProviderARNs:
        - { Fn::GetAtt: [ApiGatewayWithAuthorizationUserPool, Arn] } # リンク記事ではApiGatewayWithAuthorizationUserPoolをテンプレート内に含めているので、この書き方
```
