### ISSUE TITLE
技術検証 - DynamoDBをローカルで動かす

### ISSUE THREAD

**Issue by kawabata2018** [makes-trail/application-sample#4]
### 背景

- Lambdaと相性がいいDynamoDBを使用する選択肢を検討したい
- まだDynamoDBの動かし方を知らない
- ローカルで開発できる環境を整え、基本的な操作を確認する

### To do

- Dockerでdynamodb-localを起動できるような環境を整える
- DynamoDBで基本的なCRUDを確認する

### 完了条件

- dynamodb-localを立ち上げるDocker環境が配置されている
- 基本的な操作がメモにまとめられている

**Comment by kawabata2018** [comment]
https://www.npmjs.com/package/dynamodb-admin

```
npm install -g dynamodb-admin
 
# For Windows: 
export DYNAMO_ENDPOINT=http://localhost:8000
dynamodb-admin
 
# For Mac/Linux: 
DYNAMO_ENDPOINT=http://localhost:8000 dynamodb-admin
```

**Comment by kawabata2018** [comment]
```
DYNAMO_ENDPOINT=http://localhost:50000
dynamodb-admin -o -p 50001
```

**Comment by kawabata2018** [comment]
## dynamodb-adminが使えない？

### 発生状況
- ネット記事を参考にして下のようなdocker-compose.ymlを作成してみたが、
http://localhost:8001 を開いても想定されるGUIのページが表示されない。

```yml
version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local
    user: root
    command: -jar DynamoDBLocal.jar -dbPath /home/dynamodblocal/data -sharedDb
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb

volumes:
  dynamodb-data:
```

- ところが下のように書き換えてやると、問題なくhttp://localhost:8001 のページが表示される

```
command: -jar DynamoDBLocal.jar -dbPath /home/dynamodblocal/data -sharedDb
↓
command: -jar DynamoDBLocal.jar -inMemory
```

### 予想される発生原因
